Repository marianagsoares/helpr-front-jfs5, pull requests merged in 2022-12, with the labels that each got.

#16 Renderizar futuros clientes
  package-lock.json
  package.json
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/futurocliente.ts
  src/app/services/chamado.service.ts
  src/app/services/futurocliente.service.ts
  src/app/views/chamados/chamados-routing.module.ts
  src/app/views/chamados/chamados.module.ts
  src/app/views/chamados/chamados/chamados.component.html
  src/app/views/chamados/edit-chamado/edit-chamado.component.css
  src/app/views/chamados/edit-chamado/edit-chamado.component.html
  src/app/views/chamados/edit-chamado/edit-chamado.component.ts
  src/app/views/chamados/new-chamado/new-chamado.component.html
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/clientes/clientes.module.ts
  src/app/views/clientes/futurocliente/futurocliente.component.css
  src/app/views/clientes/futurocliente/futurocliente.component.html
  src/app/views/clientes/futurocliente/futurocliente.component.ts
Labels: enhancement

#23 criação de pipe para foto do componente usuario
  src/app/app.module.ts
  src/app/pipe/foto-funcionario.pipe.ts
  src/app/services/chamado.service.ts
  src/app/views/chamados/edit-chamado/edit-chamado.component.html
  src/app/views/chamados/edit-chamado/edit-chamado.component.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.css
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.html
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.ts
Labels: bug, enhancement

#26 Criação da página para renderizar Futuros candidatos
  src/app/app.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/futuro-candidato.ts
  src/app/services/futuro-candidato.service.ts
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/clientes/clientes.module.ts
  src/app/views/clientes/futuro-candidato/futuro-candidato.component.css
  src/app/views/clientes/futuro-candidato/futuro-candidato.component.html
  src/app/views/clientes/futuro-candidato/futuro-candidato.component.ts
Labels: enhancement

#20 Mascara telefone cpf
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/views/clientes/clientes.module.ts
  src/app/views/clientes/clientes/clientes.component.html
  src/app/views/clientes/edit-cliente/edit-cliente.component.html
  src/app/views/clientes/new-cliente/new-cliente.component.html
Labels: enhancement

#29 Possibilitando ao usuário a exclusão de um futuro candidato
  src/app/services/futuro-candidato.service.ts
  src/app/views/clientes/futuro-candidato/futuro-candidato.component.html
  src/app/views/clientes/futuro-candidato/futuro-candidato.component.ts
Labels: enhancement

#31 Criação da página para visualizar a relação de cargos
  src/app/app-routing.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/cargo.ts
  src/app/services/cargo.service.ts
  src/app/views/cargo/cargo-routing.module.ts
  src/app/views/cargo/cargo.module.ts
  src/app/views/cargo/cargo/cargo.component.css
  src/app/views/cargo/cargo/cargo.component.html
  src/app/views/cargo/cargo/cargo.component.ts
Labels: enhancement

#32 Criar título para as páginas e definir rota padrão para home
  src/app/app-routing.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/views/cargo/cargo-routing.module.ts
  src/app/views/chamados/chamados-routing.module.ts
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/clientes/futurocliente/futurocliente.component.html
  src/app/views/funcionarios/funcionarios-routing.module.ts
  src/app/views/home/home-routing.module.ts
  src/app/views/login/login-routing.module.ts
  src/assets/favicon.ico
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/assets/img/1.png
  src/assets/img/3.png
  src/assets/img/5.png
  src/assets/img/ext1.png
  src/assets/img/ext2.png
  src/assets/img/ext3.png
  src/assets/img/ext4.png
  src/assets/img/icons8-facebook-novo-24.png
  src/assets/img/icons8-instagram-24.png
  src/assets/img/icons8-linkedin-24.png
  src/assets/img/icons8-twitter-24.png
  src/assets/img/quad1.png
  src/assets/img/quad2.png
  src/assets/img/quad3.png
  src/assets/img/quad4.png
  src/assets/img/txt1.png
  src/assets/img/txt2.png
  src/assets/img/txt3.png
  src/assets/img/txt4.png
  src/assets/img/txt5.jpeg
Labels: enhancement

#35 Criar novo futuro cliente
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/components.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/services/futurocliente.service.ts
  src/app/shared/material/material.module.ts
  src/app/views/clientes/clientes.module.ts
  src/app/views/clientes/futurocliente/futurocliente.component.css
  src/app/views/clientes/futurocliente/futurocliente.component.html
  src/app/views/clientes/futurocliente/new-futuro-cliente/new-futuro-cliente.component.css
  src/app/views/clientes/futurocliente/new-futuro-cliente/new-futuro-cliente.component.html
  src/app/views/clientes/futurocliente/new-futuro-cliente/new-futuro-cliente.component.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/login/login.module.ts
  src/app/views/login/login/login.component.css
  src/app/views/login/login/login.component.html
  src/app/views/login/login/login.component.ts
Labels: enhancement

#38 pequenas correções realizadas nos códigos
  src/app/views/cargo/cargo-routing.module.ts
  src/app/views/cargo/cargo/cargo.component.html
  src/app/views/cargo/new-cargo/new-cargo.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
Labels: bug

#39 Criação do botão excluir cargo
  src/app/services/cargo.service.ts
  src/app/views/cargo/cargo/cargo.component.html
  src/app/views/cargo/cargo/cargo.component.ts
Labels: enhancement

#43 Carousel home
  angular.json
  package-lock.json
  package.json
  src/app/views/home/home/home.component.html
  src/index.html
Labels: enhancement

#44 Criação da página para Editar Cargo
  src/app/services/cargo.service.ts
  src/app/views/cargo/cargo-routing.module.ts
  src/app/views/cargo/cargo.module.ts
  src/app/views/cargo/edit-cargo/edit-cargo.component.css
  src/app/views/cargo/edit-cargo/edit-cargo.component.html
  src/app/views/cargo/edit-cargo/edit-cargo.component.ts
Labels: enhancement

#48 Criação do método para deletar funcionário
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
Labels: enhancement
